server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?serverTimezone=GMT%2b8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    port: 6379
    host: 127.0.0.1


  mail:
    protocol: smtps
    #配置 SMTP 服务器地址
    host: smtp.qq.com
    #发送者邮箱
    username: 2116134146@qq.com
    #配置密码,不是真正的密码，是刚刚申请到的授权码
    password: tykvglmrfwpfehff
    #端口号
    port: 465
    #默认的邮件编码 UTF-8
    default-encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml    #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: F:/BYSJ/files/

alipay:
  appId: 2021000122679161
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnkaQWalcLcLxjBgay/qTUbzvfp9PnTjv4x7hdJ09wzhnU7Z6S3ZI19SMjnuuftuyngwyaQcdt+z+RlQM9RsomuESY/OsYgyaVbh+9fYELQ7jUPyAlre8TSCCZpX9HmIXh/sdojEFAKcXJ00t6dxz3IQ+n4gSQnICwF+YVjT73So3wh088uoWUovLvx6Dlv/YKzfk81gr24uwo5s782dDtAP6g60hB+lq/Xfd/Dc3s16pXYsemHowsmVKNlHfY75eeuPcSFHC/vlQiDq6Jay0inYOoMGVnMr7iWZmks2182uBaFb5M5RBJr4WOgI3LuIhBDauu/R0WTfn5CEppb8LVAgMBAAECggEAQcccAGiR7r28VarB6nWnQnS/rhX1SrEdPZU4u+h4eLGO1lTIkKJFiMTHnG3/1Fw8Ha2Fvu/fVz7vPzidYups5DIlS2DM8HxbIwFtmDax9zgIT9jPx7q1RH5lvaqHghVPSN14bYPRAVzkdUtqL5KeXiwuNxqz7AhjQ7y95uvhMbUBQfzAQnpf0WBEfohm7Acex0pF0AT3LHgtsLNuRtXDXFxGBH+/ujRXFZ/q1+OuRB4dsmctSLNMTClHlaVGYdcxxf1kbyXkPcyOAFQ+vi6pWuMFr0BkK+6BXjlgJSJczH05HWgebkM7/PKWyXEtihDsI6w3jCciCczkkw6GR4UMgQKBgQDhK6UzpbJjVj4cmoMy+GNz+vcc1rfmD/sXlWOopOFBpzIA5mSALuigrIimSfSlSORjGXSXS5/y8AWfkZ3AeSVjh7y3we4EP+JvpjrKr8v82h9nfZtSyAdanVaSb+w+ftdMQhJQCn4wSIS8VJmrymRHhktdES7go8ZrG+o/p5x+JQKBgQC+gwb72pfIpa9FrVMup4E4JD+TE6z9ORFTFbNIeRZpKLclDCCP+JlOgNyYwdcfSdmWKxMSCz0hfczXKC1yV8Du1rrdaNhk3DJPJl2pRixrCdtszoPDggazA8P5jFymCa0l2aDMO6iMnPl4rqrjZ+ZP2WJ8i/JbPxfnY3cSCnRa8QKBgGqoJNmA/C2nlUYxPkIve9RdJR4o6vTzzukN3yXr67MQglQAzcwV7CTndNbnoxWDoIL8dMiRjtMhNFiwPfwEplwt2ItmNdsXc6eVIrYNbV945nU7/w3IKAuZCX/Vuh6kMFEz3r7BKaKvRwh6PkwsUzG6AAq2b/ECQqNLlrrOJwdtAoGBAKA/aqJyjnXyF+pODsgRkbn9k5RNWpdtZ0sx16pAYD94RgVdnA4+GAZWkjfT5PWmkuWjudjVp0gCn0jjvMaPVfQQnwIabNr59T9qkCIQqtAmbHGrjF3pg2UU58WC8XOgdAqAcqcYD4CnkZiXo5rBDJNh0VveA7AI9DxoCAIe1RyhAoGBAMxhzN9dCtMGhcfQKp9V4a6SnKF4C0SMeamE0qKfAAldm6M0c6iCAeaado99Hws//uW5OdM/rT7XXFASGgFMQu4YEMTppphLd+CB+5fCj+InO75Cf9tIuajQBdZ5aztnfDBHhY+ex80i/ShswLwyyF4sNTlaW35OLiusvyP7T5JH
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0nyQ6nfyf2Cg+4tgTTM8CVlWJSarv4bZSrsKR0kSh+2imGMex8OVDTt2QOt1eUB2qncXT9Fm9wo39WNtzFMfyt2GlgpdmQl+/GJLfy00nijeWZsUxyMLn+wrbChvxDV0a7q74LXqpwE9aWUR3uaxYnkap6Ktq5tQ5fue1t5fE92Vh20wtekUPjOnWr+UbavomsrtpMEGhi3ng+5s5VBFNRdDGgqBL2aWAfGGuLkkA7bVeddL+WVYpzIbfeK+sY9QAS1OMlFJpRoYTO3XCsFX19Q6UN5KNEXkeyKnG3RYMTTR8MRhJ2BxSolhNyk3c7W9+VZX+h+XZsu0a7ed6hvFcwIDAQAB
  notifyUrl: http://aipue8.natappfree.cc/alipay/notify