server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bysj?serverTimezone=GMT%2b8
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1

  mail:
    protocol: smtps
    #配置 SMTP 服务器地址
    host: smtp.qq.com
    #发送者邮箱
    username: 2116134146@qq.com
    #配置密码,不是真正的密码，是刚刚申请到的授权码
    password: tykvglmrfwpfehff
    #端口号
    port: 465
    #默认的邮件编码 UTF-8
    default-encoding: UTF-8


mybatis:
  mapper-locations: classpath:mapper/*.xml    #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: F:/BYSJ/files/

